
title: ZimUzo Foundation
email: your-email@domain.com
author: ENEIV
author_github: ENEIV
description: |
  a simple theme for Jekyll using Materializecss
baseurl: "/ZimUzo"
url: https:eneiv/github.io/ZimUzo

github:
  user: ENEIV
  repository: ZimUzo
  url: https://eneiv.github.io/ZimUzo
  status: true


markdown: kramdown
